<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Album', 'doctrine');

/**
 * BaseAlbum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idUsuario
 * @property string $descripcion
 * @property sfGuardUser $sfGuardUser
 * @property Doctrine_Collection $Imagen
 * 
 * @method integer             getIdUsuario()   Returns the current record's "idUsuario" value
 * @method string              getDescripcion() Returns the current record's "descripcion" value
 * @method sfGuardUser         getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method Doctrine_Collection getImagen()      Returns the current record's "Imagen" collection
 * @method Album               setIdUsuario()   Sets the current record's "idUsuario" value
 * @method Album               setDescripcion() Sets the current record's "descripcion" value
 * @method Album               setSfGuardUser() Sets the current record's "sfGuardUser" value
 * @method Album               setImagen()      Sets the current record's "Imagen" collection
 * 
 * @package    definiciones
 * @subpackage model
 * @author     Fabian Allel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAlbum extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('album');
        $this->hasColumn('idUsuario', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('descripcion', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'idUsuario',
             'foreign' => 'id'));

        $this->hasMany('Imagen', array(
             'local' => 'id',
             'foreign' => 'idAlbum'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}