<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Modulo', 'doctrine');

/**
 * BaseModulo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property text $descripcion
 * @property boolean $activo
 * @property boolean $tienePublicidad
 * @property Doctrine_Collection $Funcionalidad
 * 
 * @method string              getNombre()          Returns the current record's "nombre" value
 * @method text                getDescripcion()     Returns the current record's "descripcion" value
 * @method boolean             getActivo()          Returns the current record's "activo" value
 * @method boolean             getTienePublicidad() Returns the current record's "tienePublicidad" value
 * @method Doctrine_Collection getFuncionalidad()   Returns the current record's "Funcionalidad" collection
 * @method Modulo              setNombre()          Sets the current record's "nombre" value
 * @method Modulo              setDescripcion()     Sets the current record's "descripcion" value
 * @method Modulo              setActivo()          Sets the current record's "activo" value
 * @method Modulo              setTienePublicidad() Sets the current record's "tienePublicidad" value
 * @method Modulo              setFuncionalidad()   Sets the current record's "Funcionalidad" collection
 * 
 * @package    definiciones
 * @subpackage model
 * @author     Fabian Allel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseModulo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('modulo');
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('descripcion', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('activo', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('tienePublicidad', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => '0',
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Funcionalidad', array(
             'local' => 'id',
             'foreign' => 'idModulo'));
    }
}