<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Perfil', 'doctrine');

/**
 * BasePerfil
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $descripcion
 * @property integer $activo
 * @property integer $editable
 * @property integer $borrado
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $Permiso
 * @property Doctrine_Collection $Usuario
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getNombre()      Returns the current record's "nombre" value
 * @method string              getDescripcion() Returns the current record's "descripcion" value
 * @method integer             getActivo()      Returns the current record's "activo" value
 * @method integer             getEditable()    Returns the current record's "editable" value
 * @method integer             getBorrado()     Returns the current record's "borrado" value
 * @method timestamp           getCreatedAt()   Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()   Returns the current record's "updated_at" value
 * @method Doctrine_Collection getPermiso()     Returns the current record's "Permiso" collection
 * @method Doctrine_Collection getUsuario()     Returns the current record's "Usuario" collection
 * @method Perfil              setId()          Sets the current record's "id" value
 * @method Perfil              setNombre()      Sets the current record's "nombre" value
 * @method Perfil              setDescripcion() Sets the current record's "descripcion" value
 * @method Perfil              setActivo()      Sets the current record's "activo" value
 * @method Perfil              setEditable()    Sets the current record's "editable" value
 * @method Perfil              setBorrado()     Sets the current record's "borrado" value
 * @method Perfil              setCreatedAt()   Sets the current record's "created_at" value
 * @method Perfil              setUpdatedAt()   Sets the current record's "updated_at" value
 * @method Perfil              setPermiso()     Sets the current record's "Permiso" collection
 * @method Perfil              setUsuario()     Sets the current record's "Usuario" collection
 * 
 * @package    definiciones
 * @subpackage model
 * @author     Fabian Allel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePerfil extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('perfil');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('activo', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('editable', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('borrado', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Permiso', array(
             'local' => 'id',
             'foreign' => 'idperfil'));

        $this->hasMany('Usuario', array(
             'local' => 'id',
             'foreign' => 'idperfil'));
    }
}