<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Funcionalidad', 'doctrine');

/**
 * BaseFuncionalidad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idModulo
 * @property string $credencial
 * @property text $descripcion
 * @property enum $aplicacion
 * @property Modulo $Modulo
 * @property Doctrine_Collection $Permiso
 * 
 * @method integer             getIdModulo()    Returns the current record's "idModulo" value
 * @method string              getCredencial()  Returns the current record's "credencial" value
 * @method text                getDescripcion() Returns the current record's "descripcion" value
 * @method enum                getAplicacion()  Returns the current record's "aplicacion" value
 * @method Modulo              getModulo()      Returns the current record's "Modulo" value
 * @method Doctrine_Collection getPermiso()     Returns the current record's "Permiso" collection
 * @method Funcionalidad       setIdModulo()    Sets the current record's "idModulo" value
 * @method Funcionalidad       setCredencial()  Sets the current record's "credencial" value
 * @method Funcionalidad       setDescripcion() Sets the current record's "descripcion" value
 * @method Funcionalidad       setAplicacion()  Sets the current record's "aplicacion" value
 * @method Funcionalidad       setModulo()      Sets the current record's "Modulo" value
 * @method Funcionalidad       setPermiso()     Sets the current record's "Permiso" collection
 * 
 * @package    definiciones
 * @subpackage model
 * @author     Fabian Allel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFuncionalidad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('funcionalidad');
        $this->hasColumn('idModulo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('credencial', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('descripcion', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('aplicacion', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'administracion',
              1 => 'frontend',
             ),
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Modulo', array(
             'local' => 'idModulo',
             'foreign' => 'id'));

        $this->hasMany('Permiso', array(
             'local' => 'id',
             'foreign' => 'idFuncionalidad'));
    }
}