<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Test', 'doctrine');

/**
 * BaseTest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idUsuario
 * @property sfGuardUser $sfGuardUser
 * @property Doctrine_Collection $Respuesta
 * 
 * @method integer             getIdUsuario()   Returns the current record's "idUsuario" value
 * @method sfGuardUser         getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method Doctrine_Collection getRespuesta()   Returns the current record's "Respuesta" collection
 * @method Test                setIdUsuario()   Sets the current record's "idUsuario" value
 * @method Test                setSfGuardUser() Sets the current record's "sfGuardUser" value
 * @method Test                setRespuesta()   Sets the current record's "Respuesta" collection
 * 
 * @package    definiciones
 * @subpackage model
 * @author     Fabian Allel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTest extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('test');
        $this->hasColumn('idUsuario', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'idUsuario',
             'foreign' => 'id'));

        $this->hasMany('Respuesta', array(
             'local' => 'id',
             'foreign' => 'idTest'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}