<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RegistroDefinicion', 'doctrine');

/**
 * BaseRegistroDefinicion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idDefinicion
 * @property text $textoAnterior
 * @property text $textoPosterior
 * @property Definicion $Definicion
 * 
 * @method integer            getIdDefinicion()   Returns the current record's "idDefinicion" value
 * @method text               getTextoAnterior()  Returns the current record's "textoAnterior" value
 * @method text               getTextoPosterior() Returns the current record's "textoPosterior" value
 * @method Definicion         getDefinicion()     Returns the current record's "Definicion" value
 * @method RegistroDefinicion setIdDefinicion()   Sets the current record's "idDefinicion" value
 * @method RegistroDefinicion setTextoAnterior()  Sets the current record's "textoAnterior" value
 * @method RegistroDefinicion setTextoPosterior() Sets the current record's "textoPosterior" value
 * @method RegistroDefinicion setDefinicion()     Sets the current record's "Definicion" value
 * 
 * @package    definiciones
 * @subpackage model
 * @author     Fabian Allel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegistroDefinicion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('registroDefinicion');
        $this->hasColumn('idDefinicion', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('textoAnterior', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('textoPosterior', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Definicion', array(
             'local' => 'idDefinicion',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}