<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PalabraSubCategoria', 'doctrine');

/**
 * BasePalabraSubCategoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idPalabraCategoria
 * @property text $texto
 * @property string $imagen
 * @property PalabraCategoria $PalabraCategoria
 * 
 * @method integer             getIdPalabraCategoria() Returns the current record's "idPalabraCategoria" value
 * @method text                getTexto()              Returns the current record's "texto" value
 * @method string              getImagen()             Returns the current record's "imagen" value
 * @method PalabraCategoria    getPalabraCategoria()   Returns the current record's "PalabraCategoria" value
 * @method PalabraSubCategoria setIdPalabraCategoria() Sets the current record's "idPalabraCategoria" value
 * @method PalabraSubCategoria setTexto()              Sets the current record's "texto" value
 * @method PalabraSubCategoria setImagen()             Sets the current record's "imagen" value
 * @method PalabraSubCategoria setPalabraCategoria()   Sets the current record's "PalabraCategoria" value
 * 
 * @package    definiciones
 * @subpackage model
 * @author     Fabian Allel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePalabraSubCategoria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('palabraSubcategoria');
        $this->hasColumn('idPalabraCategoria', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('texto', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('imagen', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PalabraCategoria', array(
             'local' => 'idPalabraCategoria',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}