<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PublicacionMuro', 'doctrine');

/**
 * BasePublicacionMuro
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idUsuario
 * @property integer $idUsuarioEscribe
 * @property text $publicacion
 * @property string $archivo
 * @property boolean $borrado
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer         getIdUsuario()        Returns the current record's "idUsuario" value
 * @method integer         getIdUsuarioEscribe() Returns the current record's "idUsuarioEscribe" value
 * @method text            getPublicacion()      Returns the current record's "publicacion" value
 * @method string          getArchivo()          Returns the current record's "archivo" value
 * @method boolean         getBorrado()          Returns the current record's "borrado" value
 * @method sfGuardUser     getSfGuardUser()      Returns the current record's "sfGuardUser" value
 * @method PublicacionMuro setIdUsuario()        Sets the current record's "idUsuario" value
 * @method PublicacionMuro setIdUsuarioEscribe() Sets the current record's "idUsuarioEscribe" value
 * @method PublicacionMuro setPublicacion()      Sets the current record's "publicacion" value
 * @method PublicacionMuro setArchivo()          Sets the current record's "archivo" value
 * @method PublicacionMuro setBorrado()          Sets the current record's "borrado" value
 * @method PublicacionMuro setSfGuardUser()      Sets the current record's "sfGuardUser" value
 * 
 * @package    definiciones
 * @subpackage model
 * @author     Fabian Allel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePublicacionMuro extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('publicacionMuro');
        $this->hasColumn('idUsuario', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('idUsuarioEscribe', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('publicacion', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('archivo', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('borrado', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => '0',
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'idUsuario',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}