<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RegistroDefinicion', 'doctrine');

/**
 * BaseRegistroDefinicion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $iddefinicion
 * @property string $textoanterior
 * @property string $textoposterior
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer            getIddefinicion()   Returns the current record's "iddefinicion" value
 * @method string             getTextoanterior()  Returns the current record's "textoanterior" value
 * @method string             getTextoposterior() Returns the current record's "textoposterior" value
 * @method timestamp          getCreatedAt()      Returns the current record's "created_at" value
 * @method timestamp          getUpdatedAt()      Returns the current record's "updated_at" value
 * @method RegistroDefinicion setIddefinicion()   Sets the current record's "iddefinicion" value
 * @method RegistroDefinicion setTextoanterior()  Sets the current record's "textoanterior" value
 * @method RegistroDefinicion setTextoposterior() Sets the current record's "textoposterior" value
 * @method RegistroDefinicion setCreatedAt()      Sets the current record's "created_at" value
 * @method RegistroDefinicion setUpdatedAt()      Sets the current record's "updated_at" value
 * 
 * @package    definiciones
 * @subpackage model
 * @author     Fabian Allel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegistroDefinicion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('registroDefinicion');
        $this->hasColumn('iddefinicion', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('textoanterior', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('textoposterior', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}