<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RegistroPalabra', 'doctrine');

/**
 * BaseRegistroPalabra
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idPalabra
 * @property text $textoPalabraAnterior
 * @property text $textoPalabraPosterior
 * @property text $textoDefinicionAnterior
 * @property text $textoDefinicionPosterior
 * @property Palabra $Palabra
 * 
 * @method integer         getIdPalabra()                Returns the current record's "idPalabra" value
 * @method text            getTextoPalabraAnterior()     Returns the current record's "textoPalabraAnterior" value
 * @method text            getTextoPalabraPosterior()    Returns the current record's "textoPalabraPosterior" value
 * @method text            getTextoDefinicionAnterior()  Returns the current record's "textoDefinicionAnterior" value
 * @method text            getTextoDefinicionPosterior() Returns the current record's "textoDefinicionPosterior" value
 * @method Palabra         getPalabra()                  Returns the current record's "Palabra" value
 * @method RegistroPalabra setIdPalabra()                Sets the current record's "idPalabra" value
 * @method RegistroPalabra setTextoPalabraAnterior()     Sets the current record's "textoPalabraAnterior" value
 * @method RegistroPalabra setTextoPalabraPosterior()    Sets the current record's "textoPalabraPosterior" value
 * @method RegistroPalabra setTextoDefinicionAnterior()  Sets the current record's "textoDefinicionAnterior" value
 * @method RegistroPalabra setTextoDefinicionPosterior() Sets the current record's "textoDefinicionPosterior" value
 * @method RegistroPalabra setPalabra()                  Sets the current record's "Palabra" value
 * 
 * @package    definiciones
 * @subpackage model
 * @author     Fabian Allel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegistroPalabra extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('registroPalabra');
        $this->hasColumn('idPalabra', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('textoPalabraAnterior', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('textoPalabraPosterior', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('textoDefinicionAnterior', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('textoDefinicionPosterior', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Palabra', array(
             'local' => 'idPalabra',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}