<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Permiso', 'doctrine');

/**
 * BasePermiso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idPerfil
 * @property integer $idFuncionalidad
 * @property Perfil $Perfil
 * @property Funcionalidad $Funcionalidad
 * 
 * @method integer       getIdPerfil()        Returns the current record's "idPerfil" value
 * @method integer       getIdFuncionalidad() Returns the current record's "idFuncionalidad" value
 * @method Perfil        getPerfil()          Returns the current record's "Perfil" value
 * @method Funcionalidad getFuncionalidad()   Returns the current record's "Funcionalidad" value
 * @method Permiso       setIdPerfil()        Sets the current record's "idPerfil" value
 * @method Permiso       setIdFuncionalidad() Sets the current record's "idFuncionalidad" value
 * @method Permiso       setPerfil()          Sets the current record's "Perfil" value
 * @method Permiso       setFuncionalidad()   Sets the current record's "Funcionalidad" value
 * 
 * @package    definiciones
 * @subpackage model
 * @author     Fabian Allel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePermiso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('permiso');
        $this->hasColumn('idPerfil', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('idFuncionalidad', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Perfil', array(
             'local' => 'idPerfil',
             'foreign' => 'id'));

        $this->hasOne('Funcionalidad', array(
             'local' => 'idFuncionalidad',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}