<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Amigo', 'doctrine');

/**
 * BaseAmigo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idUsuario
 * @property integer $idUsuarioAmigo
 * @property Doctrine_Collection $sfGuardUser
 * 
 * @method integer             getIdUsuario()      Returns the current record's "idUsuario" value
 * @method integer             getIdUsuarioAmigo() Returns the current record's "idUsuarioAmigo" value
 * @method Doctrine_Collection getSfGuardUser()    Returns the current record's "sfGuardUser" collection
 * @method Amigo               setIdUsuario()      Sets the current record's "idUsuario" value
 * @method Amigo               setIdUsuarioAmigo() Sets the current record's "idUsuarioAmigo" value
 * @method Amigo               setSfGuardUser()    Sets the current record's "sfGuardUser" collection
 * 
 * @package    definiciones
 * @subpackage model
 * @author     Fabian Allel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAmigo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('amigo');
        $this->hasColumn('idUsuario', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('idUsuarioAmigo', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUser', array(
             'local' => 'idUsuarioAmigo',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}