<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Respuesta', 'doctrine');

/**
 * BaseRespuesta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idTest
 * @property text $textoRespuesta
 * @property boolean $respuestaCorrecta
 * @property Test $Test
 * 
 * @method integer   getIdTest()            Returns the current record's "idTest" value
 * @method text      getTextoRespuesta()    Returns the current record's "textoRespuesta" value
 * @method boolean   getRespuestaCorrecta() Returns the current record's "respuestaCorrecta" value
 * @method Test      getTest()              Returns the current record's "Test" value
 * @method Respuesta setIdTest()            Sets the current record's "idTest" value
 * @method Respuesta setTextoRespuesta()    Sets the current record's "textoRespuesta" value
 * @method Respuesta setRespuestaCorrecta() Sets the current record's "respuestaCorrecta" value
 * @method Respuesta setTest()              Sets the current record's "Test" value
 * 
 * @package    definiciones
 * @subpackage model
 * @author     Fabian Allel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRespuesta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('respuesta');
        $this->hasColumn('idTest', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('textoRespuesta', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('respuestaCorrecta', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => '0',
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Test', array(
             'local' => 'idTest',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}