<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Contenido', 'doctrine');

/**
 * BaseContenido
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idUsuario
 * @property integer $idCategoriaContenido
 * @property string $titulo
 * @property text $contenido
 * @property boolean $borrado
 * @property boolean $activo
 * @property sfGuardUser $sfGuardUser
 * @property CategoriaContenido $CategoriaContenido
 * 
 * @method integer            getIdUsuario()            Returns the current record's "idUsuario" value
 * @method integer            getIdCategoriaContenido() Returns the current record's "idCategoriaContenido" value
 * @method string             getTitulo()               Returns the current record's "titulo" value
 * @method text               getContenido()            Returns the current record's "contenido" value
 * @method boolean            getBorrado()              Returns the current record's "borrado" value
 * @method boolean            getActivo()               Returns the current record's "activo" value
 * @method sfGuardUser        getSfGuardUser()          Returns the current record's "sfGuardUser" value
 * @method CategoriaContenido getCategoriaContenido()   Returns the current record's "CategoriaContenido" value
 * @method Contenido          setIdUsuario()            Sets the current record's "idUsuario" value
 * @method Contenido          setIdCategoriaContenido() Sets the current record's "idCategoriaContenido" value
 * @method Contenido          setTitulo()               Sets the current record's "titulo" value
 * @method Contenido          setContenido()            Sets the current record's "contenido" value
 * @method Contenido          setBorrado()              Sets the current record's "borrado" value
 * @method Contenido          setActivo()               Sets the current record's "activo" value
 * @method Contenido          setSfGuardUser()          Sets the current record's "sfGuardUser" value
 * @method Contenido          setCategoriaContenido()   Sets the current record's "CategoriaContenido" value
 * 
 * @package    definiciones
 * @subpackage model
 * @author     Fabian Allel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContenido extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('contenido');
        $this->hasColumn('idUsuario', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('idCategoriaContenido', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('titulo', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('contenido', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('borrado', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => '0',
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('activo', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => '0',
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'idUsuario',
             'foreign' => 'id'));

        $this->hasOne('CategoriaContenido', array(
             'local' => 'idCategoriaContenido',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}