<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ImagenPiso', 'doctrine');

/**
 * BaseImagenPiso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idPiso
 * @property string $descripcion
 * @property string $imagen
 * @property Piso $Piso
 * 
 * @method integer    getIdPiso()      Returns the current record's "idPiso" value
 * @method string     getDescripcion() Returns the current record's "descripcion" value
 * @method string     getImagen()      Returns the current record's "imagen" value
 * @method Piso       getPiso()        Returns the current record's "Piso" value
 * @method ImagenPiso setIdPiso()      Sets the current record's "idPiso" value
 * @method ImagenPiso setDescripcion() Sets the current record's "descripcion" value
 * @method ImagenPiso setImagen()      Sets the current record's "imagen" value
 * @method ImagenPiso setPiso()        Sets the current record's "Piso" value
 * 
 * @package    definiciones
 * @subpackage model
 * @author     Fabian Allel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseImagenPiso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('imagenPiso');
        $this->hasColumn('idPiso', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('descripcion', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('imagen', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Piso', array(
             'local' => 'idPiso',
             'foreign' => 'id',
             'onDelete' => 'Cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}