<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PalabraCategoria', 'doctrine');

/**
 * BasePalabraCategoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $texto
 * @property string $imagen
 * @property Doctrine_Collection $Palabra
 * @property Doctrine_Collection $PalabraSubCategoria
 * 
 * @method text                getTexto()               Returns the current record's "texto" value
 * @method string              getImagen()              Returns the current record's "imagen" value
 * @method Doctrine_Collection getPalabra()             Returns the current record's "Palabra" collection
 * @method Doctrine_Collection getPalabraSubCategoria() Returns the current record's "PalabraSubCategoria" collection
 * @method PalabraCategoria    setTexto()               Sets the current record's "texto" value
 * @method PalabraCategoria    setImagen()              Sets the current record's "imagen" value
 * @method PalabraCategoria    setPalabra()             Sets the current record's "Palabra" collection
 * @method PalabraCategoria    setPalabraSubCategoria() Sets the current record's "PalabraSubCategoria" collection
 * 
 * @package    definiciones
 * @subpackage model
 * @author     Fabian Allel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePalabraCategoria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('palabraCategoria');
        $this->hasColumn('texto', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('imagen', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Palabra', array(
             'local' => 'id',
             'foreign' => 'idPalabraCategoria'));

        $this->hasMany('PalabraSubCategoria', array(
             'local' => 'id',
             'foreign' => 'idPalabraCategoria'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}