<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Definicion', 'doctrine');

/**
 * BaseDefinicion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idPalabra
 * @property text $texto
 * @property string $imagen
 * @property Palabra $Palabra
 * @property Doctrine_Collection $RegistroDefinicion
 * 
 * @method integer             getIdPalabra()          Returns the current record's "idPalabra" value
 * @method text                getTexto()              Returns the current record's "texto" value
 * @method string              getImagen()             Returns the current record's "imagen" value
 * @method Palabra             getPalabra()            Returns the current record's "Palabra" value
 * @method Doctrine_Collection getRegistroDefinicion() Returns the current record's "RegistroDefinicion" collection
 * @method Definicion          setIdPalabra()          Sets the current record's "idPalabra" value
 * @method Definicion          setTexto()              Sets the current record's "texto" value
 * @method Definicion          setImagen()             Sets the current record's "imagen" value
 * @method Definicion          setPalabra()            Sets the current record's "Palabra" value
 * @method Definicion          setRegistroDefinicion() Sets the current record's "RegistroDefinicion" collection
 * 
 * @package    definiciones
 * @subpackage model
 * @author     Fabian Allel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDefinicion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('definicion');
        $this->hasColumn('idPalabra', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('texto', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('imagen', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Palabra', array(
             'local' => 'idPalabra',
             'foreign' => 'id'));

        $this->hasMany('RegistroDefinicion', array(
             'local' => 'id',
             'foreign' => 'idDefinicion'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}