<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ImagenPerfil', 'doctrine');

/**
 * BaseImagenPerfil
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idUsuario
 * @property text $descripcion
 * @property string $imagen
 * @property sfGuardUser $sfGuardUser
 * 
 * @method integer      getIdUsuario()   Returns the current record's "idUsuario" value
 * @method text         getDescripcion() Returns the current record's "descripcion" value
 * @method string       getImagen()      Returns the current record's "imagen" value
 * @method sfGuardUser  getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method ImagenPerfil setIdUsuario()   Sets the current record's "idUsuario" value
 * @method ImagenPerfil setDescripcion() Sets the current record's "descripcion" value
 * @method ImagenPerfil setImagen()      Sets the current record's "imagen" value
 * @method ImagenPerfil setSfGuardUser() Sets the current record's "sfGuardUser" value
 * 
 * @package    definiciones
 * @subpackage model
 * @author     Fabian Allel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseImagenPerfil extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('imagenPerfil');
        $this->hasColumn('idUsuario', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('descripcion', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('imagen', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'idUsuario',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}