<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CategoriaContenido', 'doctrine');

/**
 * BaseCategoriaContenido
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $texto
 * @property string $imagen
 * @property Doctrine_Collection $Contenido
 * 
 * @method text                getTexto()     Returns the current record's "texto" value
 * @method string              getImagen()    Returns the current record's "imagen" value
 * @method Doctrine_Collection getContenido() Returns the current record's "Contenido" collection
 * @method CategoriaContenido  setTexto()     Sets the current record's "texto" value
 * @method CategoriaContenido  setImagen()    Sets the current record's "imagen" value
 * @method CategoriaContenido  setContenido() Sets the current record's "Contenido" collection
 * 
 * @package    definiciones
 * @subpackage model
 * @author     Fabian Allel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoriaContenido extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('categoriaContenido');
        $this->hasColumn('texto', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('imagen', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Contenido', array(
             'local' => 'id',
             'foreign' => 'idCategoriaContenido'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}