<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Imagen', 'doctrine');

/**
 * BaseImagen
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idAlbum
 * @property string $descripcion
 * @property string $imagen
 * @property Album $Album
 * 
 * @method integer getIdAlbum()     Returns the current record's "idAlbum" value
 * @method string  getDescripcion() Returns the current record's "descripcion" value
 * @method string  getImagen()      Returns the current record's "imagen" value
 * @method Album   getAlbum()       Returns the current record's "Album" value
 * @method Imagen  setIdAlbum()     Sets the current record's "idAlbum" value
 * @method Imagen  setDescripcion() Sets the current record's "descripcion" value
 * @method Imagen  setImagen()      Sets the current record's "imagen" value
 * @method Imagen  setAlbum()       Sets the current record's "Album" value
 * 
 * @package    definiciones
 * @subpackage model
 * @author     Fabian Allel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseImagen extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('imagen');
        $this->hasColumn('idAlbum', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('descripcion', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('imagen', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Album', array(
             'local' => 'idAlbum',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}