<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RegistroPalabra', 'doctrine');

/**
 * BaseRegistroPalabra
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idPalabra
 * @property text $textoAnterior
 * @property text $textoPosterior
 * @property Palabra $Palabra
 * 
 * @method integer         getIdPalabra()      Returns the current record's "idPalabra" value
 * @method text            getTextoAnterior()  Returns the current record's "textoAnterior" value
 * @method text            getTextoPosterior() Returns the current record's "textoPosterior" value
 * @method Palabra         getPalabra()        Returns the current record's "Palabra" value
 * @method RegistroPalabra setIdPalabra()      Sets the current record's "idPalabra" value
 * @method RegistroPalabra setTextoAnterior()  Sets the current record's "textoAnterior" value
 * @method RegistroPalabra setTextoPosterior() Sets the current record's "textoPosterior" value
 * @method RegistroPalabra setPalabra()        Sets the current record's "Palabra" value
 * 
 * @package    definiciones
 * @subpackage model
 * @author     Fabian Allel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegistroPalabra extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('registroPalabra');
        $this->hasColumn('idPalabra', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('textoAnterior', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('textoPosterior', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Palabra', array(
             'local' => 'idPalabra',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}