<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Palabra', 'doctrine');

/**
 * BasePalabra
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idUsuario
 * @property text $textoPalabra
 * @property text $textoDefinicion
 * @property string $imagen
 * @property sfGuardUser $sfGuardUser
 * @property Doctrine_Collection $RegistroPalabra
 * @property Categoria $Categoria
 * 
 * @method integer             getIdUsuario()       Returns the current record's "idUsuario" value
 * @method text                getTextoPalabra()    Returns the current record's "textoPalabra" value
 * @method text                getTextoDefinicion() Returns the current record's "textoDefinicion" value
 * @method string              getImagen()          Returns the current record's "imagen" value
 * @method sfGuardUser         getSfGuardUser()     Returns the current record's "sfGuardUser" value
 * @method Doctrine_Collection getRegistroPalabra() Returns the current record's "RegistroPalabra" collection
 * @method Categoria           getCategoria()       Returns the current record's "Categoria" value
 * @method Palabra             setIdUsuario()       Sets the current record's "idUsuario" value
 * @method Palabra             setTextoPalabra()    Sets the current record's "textoPalabra" value
 * @method Palabra             setTextoDefinicion() Sets the current record's "textoDefinicion" value
 * @method Palabra             setImagen()          Sets the current record's "imagen" value
 * @method Palabra             setSfGuardUser()     Sets the current record's "sfGuardUser" value
 * @method Palabra             setRegistroPalabra() Sets the current record's "RegistroPalabra" collection
 * @method Palabra             setCategoria()       Sets the current record's "Categoria" value
 * 
 * @package    definiciones
 * @subpackage model
 * @author     Fabian Allel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePalabra extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('palabra');
        $this->hasColumn('idUsuario', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('textoPalabra', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('textoDefinicion', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('imagen', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'idUsuario',
             'foreign' => 'id'));

        $this->hasMany('RegistroPalabra', array(
             'local' => 'id',
             'foreign' => 'idPalabra'));

        $this->hasOne('Categoria', array(
             'local' => 'id',
             'foreign' => 'idPalabra'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}