<?php

/**
 * BandejaEntradaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BandejaEntradaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BandejaEntradaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BandejaEntrada');
    }
    
    
                 public function obtenerNombreById($id){
        $q = Doctrine_Query::create()
	            ->select('u.username')
	            ->from('sfGuardUser u')
                     ->where('u.id= ? ',$id);


	   $u=$q->fetchOne();
	     if ($u) {
                 return $u;
	     }else{
                 return "Este usuario ya no existe";
             }
         }
}