<?php

/**
 * BandejaEntradaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BandejaEntradaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BandejaEntradaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BandejaEntrada');
    }
}