<?php

/**
 * CategoriaContenidoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoriaContenidoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoriaContenidoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoriaContenido');
    }
    
    public function getLista() {	     
          
    $q = Doctrine_Query::create()
    ->select('t.id, t.texto')
    ->from('CategoriaContenido t')
    ->orderBy('t.id DESC');
       $q->fetchArray();
       
  $resultados=$q->fetchArray();
	     if (!$resultados) {
	     	return false;
	     }
	     else {
	     	foreach ($resultados as $resultado) {
	     		$retorno[$resultado['id']]=$resultado['texto'];
	     	}
	     	
	     	return $retorno;
	     }
	     	
  
}


     public function verificarExiste($nombre){
        $q = Doctrine_Query::create()
	            ->select('u.*')
	            ->from('CategoriaContenido u')
                     ->where('u.texto = ? ',$nombre);

	   $u=$q->fetchOne();
	     if ($u) {
                 //si ya esta en la base de datos
	 		return true;
	     }else{
                 //si no esta en la base de datos
	 		return false;
             }
         }
}