<?php

/**
 * DocumentoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocumentoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DocumentoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Documento');
    }
    
    
    
        
             public function verificarExiste($idUsuario, $titulo){
        $q = Doctrine_Query::create()
	            ->select('u.*')
	            ->from('Documento u')
                     ->where('u.titulo LIKE ? ',$nombre)
                     ->andWhere('u.idUsuario =?',$idUsuario);

	   $u=$q->fetchOne();
	     if ($u) {
                 //si ya esta en la base de datos
	 		return true;
	     }else{
                 //si no esta en la base de datos
	 		return false;
             }
         }
}