<?php

/**
 * FuncionalidadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FuncionalidadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FuncionalidadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Funcionalidad');
    }
}