<?php

/**
 * ModuloTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModuloTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModuloTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Modulo');
    }
}