<?php

/**
 * PalabraCategoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PalabraCategoriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PalabraCategoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PalabraCategoria');
    }
}