<?php

/**
 * PalabraTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PalabraTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PalabraTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Palabra');
    }
}