<?php

/**
 * PisoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PisoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PisoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Piso');
    }
    
    
          public function obtenerByCoordenadas($X,$Y)
  {
    $query = Doctrine_Core::getTable('Piso')->createQuery('u')
      ->where('u.coordenadaX = ?', $X)
      ->where('u.coordenadaY = ?',$Y);      

     $u=$query->fetchOne();
     
     if ($u) {
                 //si ya esta en la base de datos
	 		return $u;
	     }else{
                 //si no esta en la base de datos
	 		return false;
             }
     
  }
  
    
    
    
                 public function verificarExiste($idUsuario, $direccion){
        $q = Doctrine_Query::create()
	            ->select('u.*')
	            ->from('Piso u')
                     ->where('u.direccion LIKE ? ',$direccion);

	   $u=$q->fetchOne();
	     if ($u) {
                 //si ya esta en la base de datos
	 		return true;
	     }else{
                 //si no esta en la base de datos
	 		return false;
             }
         }
}