# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }


#default
default_index:
  url:   /inicio
  param: { module: default, action: index }
  

default_new:
  url:   /nueva
  param: { module: default, action: new }
  
  
default_create:
  url:   /crear
  param: { module: default, action: create }  
  
default_edit:
  url:   /editar
  param: { module: default, action: edit }
  
default_update:
  url:   /actualizar
  param: { module: default, action: update }  
  
default_delete:
  url:   /eliminar
  param: { module: default, action: delete }

default_show:
  url:   /mostrar
  param: { module: default, action: show }
  
  
default_getSubCategoriasOptions:
  url:   /subcategorias
  param: { module: default, action: getSubCategoriasOptions }   
  
  
  #estudiar
  
estudiar_index:
  url:   /panel-estudios
  param: { module: estudiar, action: index }  
  
estudiar_listado:
  url:   /listado
  param: { module: estudiar, action: listado }    
  
  
estudiar_prueba:
  url:   /examen
  param: { module: estudiar, action: prueba }      
  
estudiar_responder:
  url:   /respuesta
  param: { module: estudiar, action: responder }       
  
  
 #usuario 
  
usuario_editarUsuario:
  url:   /editar-usuario
  param: { module: usuario, action: editarUsuario }    
  
usuario_update:
  url:   /actualizar-usuario
  param: { module: usuario, action: update }      
  
usuario_index:
  url:   /usuario
  param: { module: usuario, action: index }       
  

sf_guard_signin:
          url:   /login
          param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
          url:   /logout
          param: { module: sfGuardAuth, action: signout }

sf_guard_password:
          url:   /request_password
          param: { module: sfGuardAuth, action: password }  

sf_guard_register:
          url:   /register
          param: { module: sfGuardRegister, action: index }   

sf_guard_forgot_password:
          url:   /forgotPassword
          param: { module: sfGuardForgotPassword, action: index }     



default_listado:
  url: /default/listado/
  param: { module: default, action: listado }          

default_listado_page:
  url: /default/listado/:page
  param: { module: default, action: listado }
  requirements:
  page: \d+
  
estudiar_listado:
  url: /estudiar/listado/
  param: { module: estudiar, action: listado }   
  
estudiar_listado_page:
  url: /estudiar/listado/:page
  param: { module: estudiar, action: listado }
  requirements:
  page: \d+  
       
#documento
documento_index:
  url:   /mis-documentos
  param: { module: documento, action: index }
  

documento_new:
  url:   /nuevo-documento
  param: { module: documento, action: new }
  
  
documento_create:
  url:   /crear-documento
  param: { module: documento, action: create }  
  
documento_edit:
  url:   /editar-documento
  param: { module: documento, action: edit }
  
documento_update:
  url:   /actualizar-documento
  param: { module: documento, action: update }  
  
documento_delete:
  url:   /eliminar-documento
  param: { module: documento, action: delete }

documento_show:
  url:   /mostrar-documento
  param: { module: documento, action: show }


#mensaje
mensaje_index:
  url:   /mensajes
  param: { module: mensaje, action: index }
  

#bandejaEntrada
bandejaEntrada_index:
  url:   /bandeja-entrada
  param: { module: bandejaEntrada, action: index }
  

bandejaEntrada_new:
  url:   /nuevo-mensaje
  param: { module: bandejaEntrada, action: new }
  
  
bandejaEntrada_create:
  url:   /crear-mensaje
  param: { module: bandejaEntrada, action: create }  
  
bandejaEntrada_edit:
  url:   /editar-mensaje
  param: { module: bandejaEntrada, action: edit }
  
bandejaEntrada_update:
  url:   /actualizar-mensaje
  param: { module: bandejaEntrada, action: update }  
  
bandejaEntrada_delete:
  url:   /eliminar-mensaje
  param: { module: bandejaEntrada, action: delete }

bandejaEntrada_show:
  url:   /mostrar-mensaje
  param: { module: bandejaEntrada, action: show }
  
  
bandejaEntrada_responder:
  url:   /entrada-responder
  param: { module: bandejaEntrada, action: responder }  
  
  
#bandejaSalida
bandejaSalida_index:
  url:   /bandeja-salida
  param: { module: bandejaSalida, action: index }
  

bandejaSalida_new:
  url:   /nuevo-mensaje-salida
  param: { module: bandejaSalida, action: new }
  
  
bandejaSalida_create:
  url:   /crear-mensaje-salida
  param: { module: bandejaSalida, action: create }  
  
bandejaSalida_edit:
  url:   /editar-mensaje-salida
  param: { module: bandejaSalida, action: edit }
  
bandejaSalida_update:
  url:   /actualizar-mensaje-salida
  param: { module: bandejaSalida, action: update }  
  
bandejaSalida_delete:
  url:   /eliminar-mensaje-salida
  param: { module: bandejaSalida, action: delete }

bandejaSalida_show:
  url:   /mostrar-mensaje-salida
  param: { module: bandejaSalida, action: show }  

bandejaSalida_responder:
  url:   /salida-responder
  param: { module: bandejaSalida, action: responder }  