# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }


#default
default_index:
  url:   /inicio
  param: { module: default, action: index }
  
default_index_page:
  url: /default/index/:page
  param: { module: default, action: index }
  requirements:
  page: \d+ 
  
default_new:
  url:   /nueva
  param: { module: default, action: new }
  
  
default_create:
  url:   /crear
  param: { module: default, action: create }  
  
default_edit:
  url:   /editar
  param: { module: default, action: edit }
  
default_update:
  url:   /actualizar
  param: { module: default, action: update }  
  
default_delete:
  url:   /eliminar
  param: { module: default, action: delete }

default_show:
  url:   /mostrar
  param: { module: default, action: show }
  
  
default_getSubCategoriasOptions:
  url:   /subcategorias
  param: { module: default, action: getSubCategoriasOptions }   
  
default_listado:
  url: /default/listado/
  param: { module: default, action: listado }          

default_listado_page:
  url: /default/listado/:page
  param: { module: default, action: listado }
  requirements:
  page: \d+
  
default_listadoTodos:
  url: /default/listado-todos/
  param: { module: default, action: listadoTodos }          

default_listadoTodos_page:
  url: /default/listado-todos/:page
  param: { module: default, action: listadoTodos }
  requirements:
  page: \d+ 
  
default_addFavorito:
  url:   /addFavorito
  param: { module: default, action: addFavorito }  
  
default_buscar:
  url:   /buscar
  param: { module: default, action: buscar }   
  
default_buscar2:
  url:   /buscar-tus-palabras
  param: { module: default, action: buscar2 }     

default_buscar3:
  url:   /buscar-palabras
  param: { module: default, action: buscar3 }   
  
default_exportarPdf:
  url: /palabra-exportar-a-PDF/:id
  class:   sfDoctrineRoute
  options: { model: Palabra, type: object}
  param: { module: default, action: exportarPdf }
  requirements:
    id: \d+
    sf_method: [get]    
  
  
  #estudiar
  
estudiar_index:
  url:   /panel-estudios
  param: { module: estudiar, action: index }  
  
estudiar_listado:
  url:   /listado
  param: { module: estudiar, action: listado }    
  
  
estudiar_prueba:
  url:   /examen
  param: { module: estudiar, action: prueba }      
  
estudiar_responder:
  url:   /respuesta
  param: { module: estudiar, action: responder }       
  
estudiar_configurarTest:
  url:   /configurar-test
  param: { module: estudiar, action: configurarTest }     
  
estudiar_accionSeleccionados:
  url:   /configurar-test2
  param: { module: estudiar, action: accionSeleccionados }   
  
estudiar_buscarCategoria:
  url:   /categorias
  param: { module: estudiar, action: buscarCategoria }     
  
estudiar_buscar:
  url:   /buscar-estudiar
  param: { module: estudiar, action: buscar }    
 #usuario 
  
usuario_editarUsuario:
  url:   /editar-usuario
  param: { module: usuario, action: editarUsuario }    
  
usuario_update:
  url:   /actualizar-usuario
  param: { module: usuario, action: update }      
  
usuario_index:
  url:   /usuario
  param: { module: usuario, action: index }      
  
usuario_envioConfirmacion:
  url:   /envio-confirmacion
  param: { module: usuario, action: envioConfirmacion }
  
usuario_confirmarAlta:
  url:   /confirmar-alta
  param: { module: usuario, action: confirmarAlta }     
  

sf_guard_signin:
          url:   /login
          param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
          url:   /logout
          param: { module: sfGuardAuth, action: signout }

sf_guard_password:
          url:   /request_password
          param: { module: sfGuardAuth, action: password }  

sf_guard_register:
          url:   /register
          param: { module: sfGuardRegister, action: index }   

sf_guard_forgot_password:
          url:   /forgotPassword
          param: { module: sfGuardForgotPassword, action: index }     




  
estudiar_listado:
  url: /estudiar/listado/
  param: { module: estudiar, action: listado }   
  
estudiar_listado_page:
  url: /estudiar/listado/:page
  param: { module: estudiar, action: listado }
  requirements:
  page: \d+  
       
#documento
documento_index:
  url:   /mis-documentos
  param: { module: documento, action: index }
  

documento_new:
  url:   /nuevo-documento
  param: { module: documento, action: new }
  
  
documento_create:
  url:   /crear-documento
  param: { module: documento, action: create }  
  
documento_edit:
  url:   /editar-documento
  param: { module: documento, action: edit }
  
documento_update:
  url:   /actualizar-documento
  param: { module: documento, action: update }  
  
documento_delete:
  url:   /eliminar-documento
  param: { module: documento, action: delete }

documento_show:
  url:   /mostrar-documento
  param: { module: documento, action: show }
  
documento_exportarPdf:
  url: /exportar-a-PDF/:id
  class:   sfDoctrineRoute
  options: { model: Documento, type: object}
  param: { module: documento, action: exportarPdf }
  requirements:
    id: \d+
    sf_method: [get]   
    
documento_index_page:
  url: /documento/index/:page
  param: { module: documento, action: index }
  requirements:
  page: \d+     
  
documento_buscar:
  url:   /buscar-documento
  param: { module: documento, action: buscar }     
  


#mensaje
mensaje_index:
  url:   /mensajes
  param: { module: mensaje, action: index }
  

#bandejaEntrada
bandejaEntrada_index:
  url:   /bandeja-entrada
  param: { module: bandejaEntrada, action: index }
  
bandejaEntrada_index_page:
  url: /bandejaEntrada/index/:page
  param: { module: bandejaEntrada, action: index }
  requirements:
  page: \d+   

bandejaEntrada_new:
  url:   /nuevo-mensaje
  param: { module: bandejaEntrada, action: new }
  
  
bandejaEntrada_create:
  url:   /crear-mensaje
  param: { module: bandejaEntrada, action: create }  
  
bandejaEntrada_edit:
  url:   /editar-mensaje
  param: { module: bandejaEntrada, action: edit }
  
bandejaEntrada_update:
  url:   /actualizar-mensaje
  param: { module: bandejaEntrada, action: update }  
  
bandejaEntrada_delete:
  url:   /eliminar-mensaje
  param: { module: bandejaEntrada, action: delete }

bandejaEntrada_show:
  url:   /mostrar-mensaje
  param: { module: bandejaEntrada, action: show }
  
  
bandejaEntrada_responder:
  url:   /entrada-responder
  param: { module: bandejaEntrada, action: responder }  
  
  
bandejaEntrada_dentroUsuario:
  url:   /ver-mensajes
  param: { module: bandejaEntrada, action: dentroUsuario }    
  
bandejaEntrada_dentroUsuario_page:
  url: /bandejaEntrada/ver-mensajes/:page
  param: { module: bandejaEntrada, action: dentroUsuario }
  requirements:
  page: \d+   
  
bandejaEntrada_buscar:
  url:   /buscar-bandeja-entrada
  param: { module: bandejaEntrada, action: buscar }  
  
bandejaEntrada_buscarMensaje:
  url:   /buscar-bandeja-entrada-mensaje
  param: { module: bandejaEntrada, action: buscarMensaje }    
  
  
#bandejaSalida
bandejaSalida_index:
  url:   /bandeja-salida
  param: { module: bandejaSalida, action: index }
  
bandejaSalida_index_page:
  url: /bandejaSalida/index/:page
  param: { module: bandejaSalida, action: index }
  requirements:
  page: \d+   
  

bandejaSalida_new:
  url:   /nuevo-mensaje-salida
  param: { module: bandejaSalida, action: new }
  
bandejaSalida_buscar:
  url:   /buscar-usuario-mensaje-salida
  param: { module: bandejaSalida, action: buscar }  
  
  
bandejaSalida_create:
  url:   /crear-mensaje-salida
  param: { module: bandejaSalida, action: create }  
  
bandejaSalida_edit:
  url:   /editar-mensaje-salida
  param: { module: bandejaSalida, action: edit }
  
bandejaSalida_update:
  url:   /actualizar-mensaje-salida
  param: { module: bandejaSalida, action: update }  
  
bandejaSalida_delete:
  url:   /eliminar-mensaje-salida
  param: { module: bandejaSalida, action: delete }

bandejaSalida_show:
  url:   /mostrar-mensaje-salida
  param: { module: bandejaSalida, action: show }  

bandejaSalida_responder:
  url:   /salida-responder
  param: { module: bandejaSalida, action: responder }  
  
bandejaSalida_seleccionaUsuario:
  url:   /selecciona-usuario
  param: { module: bandejaSalida, action: seleccionaUsuario }    
  
bandejaSalida_seleccionaUsuario_page:
  url: /bandejaSalida/seleccionaUsuario/:page
  param: { module: bandejaSalida, action: seleccionaUsuario }
  requirements:
  page: \d+     
  
bandejaSalida_buscarMensajeSalida:
  url:   /mensaje-salida-buscar
  param: { module: bandejaSalida, action: buscarMensajeSalida }   
#test 


test_index:
  url:   /test
  param: { module: test, action: index }
  
test_show:
  url:   /detalles-test
  param: { module: test, action: show }  
  
test_index_page:
  url: /test/index/:page
  param: { module: test, action: index }
  requirements:
  page: \d+ 
  
#album 


album_index:
  url:   /album
  param: { module: album, action: index }
  
album_index_page:
  url: /album/index/:page
  param: { module: album, action: index }
  requirements:
  page: \d+   
  
album_show:
  url:   /mostrar-album
  param: { module: album, action: show }   
  
album_new:
  url:   /nuevo-album
  param: { module: album, action: new }     

album_create:
  url:   /crear-album
  param: { module: album, action: create }      
  
album_edit:
  url:   /editar-album
  param: { module: album, action: edit }      
  
album_update:
  url:   /actualizar-album
  param: { module: album, action: update }   
  
album_delete:
  url:   /borrar-album
  param: { module: album, action: delete }     
  
album_buscar:
  url:   /buscar-album
  param: { module: album, action: buscar }      
#imagen

imagen_index:
  url:   /imagen
  param: { module: imagen, action: index }     

imagen_new:
  url:   /nueva-imagen
  param: { module: imagen, action: new }      
  
imagen_create:
  url:   /crear-imagen
  param: { module: imagen, action: create }     
  
imagen_edit:
  url:   /editar-imagen
  param: { module: imagen, action: edit }  
  
imagen_update:
  url:   /actualizar-imagen
  param: { module: imagen, action: update }    
  
imagen_delete:
  url:   /borrar-imagen
  param: { module: imagen, action: delete }      
  
imagen_show:
  url:   /ver-imagen
  param: { module: imagen, action: show }        
  
  
#contenido

contenido_index:
  url:   /contenido
  param: { module: contenido, action: index }     

contenido_new:
  url:   /nuevo-contenido
  param: { module: contenido, action: new }      
  
contenido_create:
  url:   /crear-contenido
  param: { module: contenido, action: create }     
  
contenido_edit:
  url:   /editar-contenido
  param: { module: contenido, action: edit }  
  
contenido_update:
  url:   /actualizar-contenido
  param: { module: contenido, action: update }    
  
contenido_delete:
  url:   /borrar-contenido
  param: { module: contenido, action: delete }      
  
contenido_show:
  url:   /ver-contenido
  param: { module: contenido, action: show }          