# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    name:         Seria
    title:        Estudia con seria
    description:  Portal para estudios académicos, herramientas de estudio, software de estudio, bases de datos de estudio, test personalizados, plataforma de estudios, plataforma para estudiar
    keywords:     Estudiar, Web, Web Estudio, Estudiantes, Palabras, Definiciones, Test, Exámen automatico, Estudiar
    language:     es    
    robots:       index, follow

  stylesheets:    [jquery-ui-1.8.17.custom.css, main.css, frontend.css,/resources/css/jquery.toastmessage.css]

  javascripts:    [jquery-1.7.1.min.j, jquery-ui-1.8.17.custom.min.js, tiny_mce/tiny_mce, mootools-1.2.5-core.js, mootools-1.2.4.4-more.js, byslidemenu-2.1.3.js]

  has_layout:     true
  layout:         layout
