<?php

/**
 * AlbumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlbumTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AlbumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Album');
    }
    
    
           public function verificarExiste($idUsuario, $nombreAlbum){
        $q = Doctrine_Query::create()
	            ->select('u.*')
	            ->from('Album u')
                     ->where('u.descripcion LIKE ? ',$nombreAlbum)
                     ->andWhere('u.idUsuario =?',$idUsuario);

	   $u=$q->fetchOne();
	     if ($u) {
                 //si ya esta en la base de datos
	 		return true;
	     }else{
                 //si no esta en la base de datos
	 		return false;
             }
         }
}