<?php

/**
 * AmigoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AmigoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AmigoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Amigo');
    }
    
           public function verificarExiste($idUsuario, $idAmigo){
        $q = Doctrine_Query::create()
	            ->select('u.*')
	            ->from('Amigo u')
                     ->where('u.idUsuario = ? ',$idUsuario)
                     ->andWhere('u.idUsuarioAmigo =? ',$idAmigo);

	   $u=$q->fetchOne();
	     if ($u) {
                 //si ya esta en la base de datos
	 		return true;
	     }else{
                 //si no esta en la base de datos
	 		return false;
             }
         }
}