<?php

/**
 * BandejaSalidaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BandejaSalidaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BandejaSalidaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BandejaSalida');
    }
}