<?php

/**
 * BandejaSalida
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    definiciones
 * @subpackage model
 * @author     Fabian Allel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class BandejaSalida extends BaseBandejaSalida
{
    
        static function obtenerUserNamePorId($id){
      $usuario= Doctrine_Core::getTable('BandejaSalida')->obtenerNombreById($id);
      
      return $usuario;
    }
}
