<?php

/**
 * CategoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Categoria');
    }
    
    
         public function verificarExiste($nombre){
        $q = Doctrine_Query::create()
	            ->select('u.*')
	            ->from('Categoria u')
                     ->where('u.texto = ? ',$nombre);

	   $u=$q->fetchOne();
	     if ($u) {
                 //si ya esta en la base de datos
	 		return true;
	     }else{
                 //si no esta en la base de datos
	 		return false;
             }
         }
}