<?php

/**
 * ContenidoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContenidoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContenidoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Contenido');
    }
}