<?php

/**
 * ContenidoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ContenidoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ContenidoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Contenido');
    }
    
         public function verificarExiste($titulo, $idCategoriaContenido){
        $q = Doctrine_Query::create()
	            ->select('u.*')
	            ->from('Contenido u')
                     ->where('u.titulo = ?',$titulo)
                     ->andWhere('u.idCategoriaContenido = ?',$idCategoriaContenido);

	   $u=$q->fetchOne();
	     if ($u) {
                 //si ya esta en la base de datos
	 		return true;
	     }else{
                 //si no esta en la base de datos
	 		return false;
             }
         }
}