<?php

/**
 * ImagenPerfilTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ImagenPerfilTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ImagenPerfilTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ImagenPerfil');
    }
}