<?php

/**
 * ImagenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ImagenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ImagenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Imagen');
    }
}