<?php

/**
 * Palabra
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    definiciones
 * @subpackage model
 * @author     Fabian Allel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Palabra extends BasePalabra
{
    
    
    public function obtenerTextoCorto(){
    $definicion=$this->getTextoDefinicion();
    
    if(strlen($definicion)>150){
        $final=substr($definicion, 0,149);
       $final=$final.'...';
        return $final;
    }else{
        return $definicion;
    }
    
    
        
    }
    
    
}
    
   
