<?php

/**
 * PalabraSubCategoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PalabraSubCategoriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PalabraSubCategoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PalabraSubCategoria');
    }
}