<?php

/**
 * PublicacionMuroTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PublicacionMuroTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PublicacionMuroTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PublicacionMuro');
    }
}