<?php

/**
 * RegistroPalabraTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RegistroPalabraTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RegistroPalabraTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RegistroPalabra');
    }
}