<?php

/**
 * RegistroDefinicionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RegistroDefinicionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RegistroDefinicionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RegistroDefinicion');
    }
}