<?php

/**
 * SubCategoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubCategoriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubCategoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SubCategoria');
    }
}