     
Palabra:
  connection: doctrine
  tableName: palabra
  actAs:
    Timestampable:
  columns:
    idUsuario:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    idCategoria:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    textoPalabra:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    textoDefinicion:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    borrado:
      type: boolean()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: "0"
      autoincrement: false
    activo:
      type: boolean()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: "0"
      autoincrement: false
    imagen:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false  
  relations:
    sfGuardUser:
      local: idUsuario
      foreign: id
      type: one
    RegistroPalabra:
      local: id
      foreign: idPalabra
      type: many 
    Categoria:
      local: idCategoria
      foreign: id
      type: one  

     
Contenido:
  connection: doctrine
  tableName: contenido
  actAs:
    Timestampable:
  columns:
    idUsuario:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    idCategoriaContenido:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    titulo:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    contenido:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    borrado:
      type: boolean()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: "0"
      autoincrement: false
    activo:
      type: boolean()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: "0"
      autoincrement: false 
  relations:
    sfGuardUser:
      local: idUsuario
      foreign: id
      type: one
    CategoriaContenido:
      local: idCategoriaContenido
      foreign: id
      type: one  
      
CategoriaContenido:
  connection: doctrine
  tableName: categoriaContenido
  actAs:
    Timestampable:
  columns:
    texto:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    imagen:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false  
  relations:
    Contenido:
      local: id
      foreign: idCategoriaContenido
      type: many




Categoria:
  connection: doctrine
  tableName: categoria
  actAs:
    Timestampable:
  columns:
    texto:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    imagen:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false  
  relations:
    Palabra:
      local: id
      foreign: idCategoria
      type: many
    SubCategoria:
      local: id
      foreign: idCategoria
      type: many   


SubCategoria:
  connection: doctrine
  tableName: subCategoria
  actAs:
    Timestampable:
  columns:
    idCategoria:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      notnull: true
      autoincrement: false
    texto:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    imagen:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false  
  relations:
    Categoria:
      local: idCategoria
      foreign: id
      type: one
      
#registros      
      
RegistroPalabra:
  connection: doctrine
  tableName: registroPalabra
  actAs:
    Timestampable:
  columns:
    idPalabra:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      notnull: true
      autoincrement: false
    textoPalabraAnterior:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    textoPalabraPosterior:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false  
    textoDefinicionAnterior:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false  
    textoDefinicionPosterior:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false  
  relations:
    Palabra:
      local: idPalabra
      foreign: id
      type: one          