    
Palabra:
  connection: doctrine
  tableName: palabra
  actAs:
    Timestampable:
  columns:
    idUsuario:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    idSubCategoria:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    textoPalabra:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    textoDefinicion:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    borrado:
      type: boolean()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: "0"
      autoincrement: false
    activo:
      type: boolean()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: "0"
      autoincrement: false
    imagen:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false  
  relations:
    sfGuardUser:
      local: idUsuario
      foreign: id
      type: one
    RegistroPalabra:
      local: id
      foreign: idPalabra
      type: many 
    SubCategoria:
      local: idSubCategoria
      foreign: id
      type: one  

     
Contenido:
  connection: doctrine
  tableName: contenido
  actAs:
    Timestampable:
  columns:
    idUsuario:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    idCategoriaContenido:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    titulo:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    contenido:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    borrado:
      type: boolean()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: "0"
      autoincrement: false
    activo:
      type: boolean()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: "0"
      autoincrement: false 
  relations:
    sfGuardUser:
      local: idUsuario
      foreign: id
      type: one
    CategoriaContenido:
      local: idCategoriaContenido
      foreign: id
      type: one  
      
CategoriaContenido:
  connection: doctrine
  tableName: categoriaContenido
  actAs:
    Timestampable:
  columns:
    texto:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    imagen:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false  
  relations:
    Contenido:
      local: id
      foreign: idCategoriaContenido
      type: many




Categoria:
  connection: doctrine
  tableName: categoria
  actAs:
    Timestampable:
  columns:
    texto:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    imagen:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false  
  relations:
    SubCategoria:
      local: id
      foreign: idCategoria
      type: many   


SubCategoria:
  connection: doctrine
  tableName: subCategoria
  actAs:
    Timestampable:
  columns:
    idCategoria:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    texto:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    imagen:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false  
  relations:
    Categoria:
      local: idCategoria
      foreign: id
      type: one
    Palabra:
      local: id
      foreign: idSubCategoria
      type: many
      
#registros      
      
RegistroPalabra:
  connection: doctrine
  tableName: registroPalabra
  actAs:
    Timestampable:
  columns:
    idPalabra:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      notnull: true
      autoincrement: false
    textoPalabraAnterior:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    textoPalabraPosterior:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false  
    textoDefinicionAnterior:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false  
    textoDefinicionPosterior:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false  
  relations:
    Palabra:
      local: idPalabra
      foreign: id
      type: one   
      

Test:
  connection: doctrine
  tableName: test
  actAs:
    Timestampable:
  columns:
    idUsuario:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    sfGuardUser:
      local: idUsuario
      foreign: id
      type: one
    Respuesta:
      local: id
      foreign: idTest
      type: many
      
      
      
Respuesta:
  connection: doctrine
  tableName: respuesta
  actAs:
    Timestampable:
  columns:
    idTest:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    textoPalabra:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false  
    textoRespuesta:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false  
    respuestaCorrecta:
      type: boolean()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: "0"
      autoincrement: false
  relations:
    Test:
      local: idTest
      foreign: id
      type: one         
      
      
Documento:
  connection: doctrine
  tableName: documento
  actAs:
    Timestampable:
  columns:
    idUsuario:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    titulo:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false      
    texto:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    imagen:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false  
  relations:
    sfGuardUser:
      local: idUsuario
      foreign: id
      type: one   
      
      
      
BandejaEntrada:
  connection: doctrine
  tableName: bandejaEntrada
  actAs:
    Timestampable:
  columns:
    idUsuarioRemitente:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false   
    idUsuarioReceptor:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false 
    mensaje:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    sfGuardUser:
      local: idUsuarioRemitente
      foreign: id
      type: one         
    sfGuardUser:
      local: idUsuarioReceptor
      foreign: id
      type: many  
      
      
      
BandejaSalida:
  connection: doctrine
  tableName: bandejaSalida
  actAs:
    Timestampable:
  columns:
    idUsuarioRemitente:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false   
    idUsuarioReceptor:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false 
    mensaje:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    sfGuardUser:
      local: idUsuarioRemitente
      foreign: id
      type: one         
    sfGuardUser:
      local: idUsuarioReceptor
      foreign: id
      type: many        
      
      
Album:
  connection: doctrine
  tableName: album
  actAs:
    Timestampable:
  columns:
    idUsuario:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false    
    descripcion:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false  
  relations:
    sfGuardUser:
      local: idUsuario
      foreign: id
      type: one         
    Imagen:
      local: id
      foreign: idAlbum
      type: many        
      
      
         
      
Imagen:
  connection: doctrine
  tableName: imagen
  actAs:
    Timestampable:
  columns:
    idAlbum:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false    
    descripcion:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false  
    imagen:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false  
  relations:
    Album:
      local: idAlbum
      foreign: id
      type: one        
      
PublicacionMuro:
  connection: doctrine
  tableName: publicacionMuro
  actAs:
    Timestampable:
  columns:
    idUsuario:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    idUsuarioEscribe:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false      
    publicacion:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    archivo:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false  
    borrado:
      type: boolean()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: "0"
      autoincrement: false
  relations:
    sfGuardUser:
      local: idUsuario
      foreign: id
      type: one      
      
      
Amigo:
  connection: doctrine
  tableName: amigo
  actAs:
    Timestampable:
  columns:
    idUsuario:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    idUsuarioAmigo:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false      
  relations:
    sfGuardUser:
      local: idUsuarioAmigo
      foreign: id
      type: many    
      
Piso:
  connection: doctrine
  tableName: piso
  actAs:
    Timestampable:
  columns:
    idUsuario:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    direccion:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    coordenadaX:
      type: float(10,6)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    coordenadaY:
      type: float(10,6)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    metro:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    linea:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false     
    pais:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true   
    contacto:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false   
    caracteristicasPrecio:
      type: text()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false  
    dormitorios:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: "0"
      autoincrement: false   
    banios:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      default: "0"
      autoincrement: false     
    precio:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false      
  relations:
    sfGuardUser:
      local: idUsuario
      foreign: id
      type: one   
    ImagenPiso:
      local: id
      foreign: idPiso
      type: many           
      onDelete: Cascade      
        
ImagenPiso:
  connection: doctrine
  tableName: imagenPiso
  actAs:
    Timestampable:
  columns:
    idPiso:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false    
    descripcion:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false  
    imagen:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false  
  relations:
    Piso:
      local: idPiso
      foreign: id
      type: one    
      onDelete: Cascade    
      
      
      